defaults:
  - _self_
  - intrinsic: rnd

env:
  name: MountainCarContinuous-v0
cats:
  fixed_reset: true
  death_not_end: true
  enable_policy_sampling: true
  reset_action:
    enable: false
    penalty: 0.0
  env_action_noise: 0.0
  teleport:
    enable: false
    type: e_greedy
    kwargs:
      e: 0.1
    memory:
      type: fifo
      capacity: 1024
train:
  initial_collection_size: 256
  total_frames: 4096
  minibatch_size: 128
algorithm:
  type: qt_opt
  gamma: 0.99
  tau: 0.005
  lr: 0.01
  update_frequency: 1
  clip_grad_norm: 1
  ensemble_number: 5
  actor:
    features: 128
  critic:
    features: 128
noise:
  scale: 0.1
  beta: 0
log:
  name: false
  checkpoint:
    enable: false
  evaluation:
    video:
      enable: false
      path:
  frames_per_epoch: 100
  path: log
seed: 0
